// Generated by Wrangler by running `wrangler types`

interface Env {
	KILO_ZONE_CACHE: KVNamespace;
	AUTH_URL: "https://dev-3drwq1geovbl2vjr.eu.auth0.com";
	CLIENT_ID: "RP8Ls2wA4DpUDBsCz7OqG97VQYbKrEKQ";
	MAX_FILE_SIZE: 104857600;
	DEV: string;
	RATE_LIMIT_SKIP_SECRET: string;
	AUTH_SECRET: string;
	CLIENT_SECRET: string;
	REDIRECT_URI: string;
	API_AUDIENCE: string;
	OBJECT_STORAGE_SIGNING_SECRET: string;
	HOSTNAME: string;
	CHAT_HANDLER_DO: DurableObjectNamespace<import("./src/index").ChatHandlerDO>;
	KILO_ZONE_OBJECT_STORAGE: R2Bucket;
	KILO_ZONE_DB: D1Database;
}
